# Generated by Django 2.1.7 on 2019-02-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_auto_20190218_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_date',), 'verbose_name': 'Posts', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='surname',
            new_name='lastname',
        ),
    ]
