# Generated by Django 2.1.7 on 2019-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_auto_20190219_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
