# Generated by Django 2.1.7 on 2019-02-22 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_app', '0009_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish_date',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
