# Generated by Django 2.1.7 on 2019-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_auto_20190222_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='website/'),
        ),
    ]
