# Generated by Django 2.1.7 on 2019-04-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_footer_current_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='company',
            field=models.CharField(default='0000000', max_length=255),
        ),
    ]
