# Generated by Django 2.1.7 on 2019-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0014_auto_20190410_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=models.CharField(default='All rights reserved', max_length=255),
        ),
    ]
