# Generated by Django 2.1.7 on 2019-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_auto_20190410_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='footer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='copyright',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_logo',
        ),
    ]
