# Generated by Django 2.1.7 on 2019-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0017_auto_20190410_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
