# Generated by Django 2.1.7 on 2019-04-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0018_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
