# Generated by Django 2.1.7 on 2019-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0019_remove_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
