# Generated by Django 2.1.7 on 2019-04-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0020_auto_20190416_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='status',
        ),
    ]
