# Generated by Django 2.1.7 on 2019-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0021_auto_20190417_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='address',
            new_name='address_visual',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='email',
            new_name='email_visual',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='telephone',
            new_name='telephone_visual',
        ),
        migrations.AddField(
            model_name='footer',
            name='address_functional',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AddField(
            model_name='footer',
            name='email_functional',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='footer',
            name='telephone_functional',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
