# Generated by Django 2.1.7 on 2019-04-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0022_auto_20190417_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='team',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
    ]
