# Generated by Django 2.1.7 on 2019-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0023_auto_20190417_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('order',), 'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(default=False),
        ),
    ]
