# Generated by Django 2.1.7 on 2019-04-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0024_auto_20190417_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_image_1', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('project_image_2', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('project_image_3', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('project_image_4', models.ImageField(blank=True, null=True, upload_to='website/')),
            ],
        ),
    ]
