# Generated by Django 2.1.7 on 2019-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0029_auto_20191209_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
