# Generated by Django 2.1.7 on 2019-12-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0031_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
