# Generated by Django 2.1.7 on 2019-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app_eng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='address_functional',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
