# Generated by Django 2.1.7 on 2019-12-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app_eng', '0002_auto_20191209_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='email_functional',
        ),
    ]
